server:
  port: 8070
  servlet.context-path: /
spring:
  flyway.enabled: false
  jersey:
    application-path: cc/api

springdoc:
  api-docs:
    path: /api-docs

spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: schema.sql
spring.jpa.properties.hibernate.format_sql: true
