server:
  port: 8070
  servlet.context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC
    username: keek_sys_api
    password: ijHgbFFt%$d657
  jersey:
    application-path: cc/api

springdoc:
  api-docs:
    path: /api-docs

